### ISSUE TITLE
Feature idea: listening medium

### ISSUE THREAD

**Issue by schambers** [RuairiD/howsmytrack-api#2]
It would be useful for reviewers to indicate what they're reviewing the song on speaker wise. 

For instance, at the time of reviewing one track I may be listening on my studio monitors/sub. Another track I may be listening to on my car speakers, etc. 

This would assist the producer in knowing where his track sounds good and what/where tweaks need to be made. 

Ideally you could make this field optional

**Comment by RuairiD** [comment]
Thanks for this Sean. I'm closing this for now and incorporating it into #3 which can be a discussion thread for all the options for submitting and writing feedback that people have suggested. If there's a lot of discussion on this point, I'll reopen this and we can discuss a route forward.
